var kanji1516 = [
{'kanji' :'友', 'hiragana':'とも', 'meaning':'Hữu - bạn', 'hannom':''},
{'kanji' :'友人', 'hiragana':'ゆうじん', 'meaning':'người bạn', 'hannom':''},
{'kanji' :'友情', 'hiragana':'ゆうじょう', 'meaning':'tình bạn', 'hannom':''},
{'kanji' :'父', 'hiragana':'ちち', 'meaning':'PHỤ', 'hannom':''},
{'kanji' :'お父さん', 'hiragana':'おとうさん', 'meaning':'cha', 'hannom':''},
{'kanji' :'父親', 'hiragana':'ちちおや', 'meaning':'Phụ Thân', 'hannom':''},
{'kanji' :'父母', 'hiragana':'ふぼ', 'meaning':'Phụ Mẫu', 'hannom':''},
{'kanji' :'母', 'hiragana':'はは', 'meaning':'MẪU', 'hannom':''},
{'kanji' :'お母さん', 'hiragana':'おかあさん', 'meaning':'mẹ', 'hannom':''},
{'kanji' :'母親', 'hiragana':'ははおや', 'meaning':'Mẫu Thân', 'hannom':''},
{'kanji' :'母国', 'hiragana':'ぼこく', 'meaning':'Mẫu Quốc', 'hannom':''},
{'kanji' :'兄', 'hiragana':'あに', 'meaning':'HUYNH', 'hannom':''},
{'kanji' :'兄弟', 'hiragana':'きょうだい', 'meaning':'Huynh Đệ', 'hannom':''},
{'kanji' :'お兄さん', 'hiragana':'おにいさん', 'meaning':'anh trai', 'hannom':''},
{'kanji' :'父兄', 'hiragana':'ふけい', 'meaning':'Phụ Huynh', 'hannom':''},
{'kanji' :'姉', 'hiragana':'あね', 'meaning':'TỶ', 'hannom':''},
{'kanji' :'お姉さん', 'hiragana':'おねえさん', 'meaning':'chị gái', 'hannom':''},
{'kanji' :'姉妹', 'hiragana':'しまい', 'meaning':'Tỷ Muội', 'hannom':''},
{'kanji' :'弟', 'hiragana':'おとうと', 'meaning':'Đệ', 'hannom':''},
{'kanji' :'弟子', 'hiragana':'でし', 'meaning':'Đệ Tử', 'hannom':''},
{'kanji' :'子弟', 'hiragana':'してい', 'meaning':'Tử Đệ', 'hannom':''},
{'kanji' :'妹', 'hiragana':'いもうと', 'meaning':'Muội', 'hannom':''},
{'kanji' :'夫', 'hiragana':'おっと', 'meaning':'PHU', 'hannom':''},
{'kanji' :'夫婦', 'hiragana':'ふうふ', 'meaning':'Phu Phụ', 'hannom':''},
{'kanji' :'夫人', 'hiragana':'ふじん', 'meaning':'Phu Nhân', 'hannom':''},
{'kanji' :'妻', 'hiragana':'つま', 'meaning':'THÊ', 'hannom':''},
{'kanji' :'夫妻', 'hiragana':'ふさい', 'meaning':'ông bà', 'hannom':''},
{'kanji' :'彼', 'hiragana':'かれ', 'meaning':'BỈ - anh ấy', 'hannom':''},
{'kanji' :'彼女', 'hiragana':'かのじょ', 'meaning':'Bỉ Nữ - cô ấy', 'hannom':''},
{'kanji' :'彼ら', 'hiragana':'かれら', 'meaning':'tụi nó', 'hannom':''},
{'kanji' :'主(な)', 'hiragana':'おもな', 'meaning':'CHỦ (yếu)', 'hannom':''},
{'kanji' :'持ち主', 'hiragana':'もちぬし', 'meaning':'chủ sở hữu', 'hannom':''},
{'kanji' :'主人', 'hiragana':'しゅじん', 'meaning':'chủ nhân', 'hannom':''},
{'kanji' :'奥', 'hiragana':'おく', 'meaning':'ÁO - sâu bên trong', 'hannom':''},
{'kanji' :'奥さん', 'hiragana':'おくさん', 'meaning':'vợ người khác', 'hannom':''},


{'kanji' :'元気', 'hiragana':'げんき', 'meaning':'NGUYÊN - nguồn', 'hannom':''},
{'kanji' :'元日', 'hiragana':'がんしつ', 'meaning':'Nguyên Nhật - ngày đầu năm', 'hannom':''},
{'kanji' :'気持ち', 'hiragana':'きもち', 'meaning':'KHÍ - cảm giác', 'hannom':''},
{'kanji' :'気分', 'hiragana':'きぶん', 'meaning':'tâm trạng', 'hannom':''},
{'kanji' :'病気', 'hiragana':'びょうき', 'meaning':'bệnh', 'hannom':''},
{'kanji' :'有る', 'hiragana':'ある', 'meaning':'HỮU - có', 'hannom':''},
{'kanji' :'有名', 'hiragana':'ゆうめい', 'meaning':'Hữu Danh - nổi tiếng', 'hannom':''},
{'kanji' :'有力', 'hiragana':'ゆうりょく', 'meaning':'Hữu Lực - mạnh mẽ', 'hannom':''},
{'kanji' :'所有する', 'hiragana':'しょゆうする', 'meaning':'Sở Hữu', 'hannom':''},
{'kanji' :'名前', 'hiragana':'なまえ', 'meaning':'DANH tiền', 'hannom':''},
{'kanji' :'名所', 'hiragana':'めいしょ', 'meaning':'Danh Sở , dang lam thắng cảnh', 'hannom':''},
{'kanji' :'名古屋', 'hiragana':'なごや', 'meaning':'tên thành phố', 'hannom':''},
{'kanji' :'名物', 'hiragana':'めいぶつ', 'meaning':'Danh Vật - đặc sản', 'hannom':''},
{'kanji' :'親', 'hiragana':'おや', 'meaning':'THÂN - cha mẹ', 'hannom':''},
{'kanji' :'親しい', 'hiragana':'したしい', 'meaning':'thân tình', 'hannom':''},
{'kanji' :'父親', 'hiragana':'ちちおや', 'meaning':'Phụ Thân - các ông bố', 'hannom':''},
{'kanji' :'新設', 'hiragana':'しんせつ', 'meaning':'Thân Thiết - tử tế', 'hannom':''},
{'kanji' :'切る', 'hiragana':'きる', 'meaning':'THIẾT - cắt', 'hannom':''},
{'kanji' :'切符', 'hiragana':'きっぷ', 'meaning':'THIẾT PHÙ - vé', 'hannom':''},
{'kanji' :'切手', 'hiragana':'きって', 'meaning':'tem thư', 'hannom':''},
{'kanji' :'大切', 'hiragana':'たいせつ', 'meaning':'Đại Thiết - quan trọng', 'hannom':''},
{'kanji' :'便り', 'hiragana':'たより', 'meaning':'Tiện - thư', 'hannom':''},
{'kanji' :'航空便', 'hiragana':'こうくうびん', 'meaning':'HÀNG KHÔNG TIệN - máy bay', 'hannom':''},
{'kanji' :'便利', 'hiragana':'べんり', 'meaning':'Tiện Lợi', 'hannom':''},
{'kanji' :'便所', 'hiragana':'べんじょ', 'meaning':'Tiện Sở -bồn cầu', 'hannom':''},
{'kanji' :'有利な', 'hiragana':'ゆうりな', 'meaning':'Hữu LỢI', 'hannom':''},
{'kanji' :'利子', 'hiragana':'りし', 'meaning':'Lợi Tử - tiền lãi', 'hannom':''},
{'kanji' :'左利き', 'hiragana':'ひだりきき', 'meaning':'Tả Lợi - thuận tay trái', 'hannom':''},
{'kanji' :'利用する', 'hiragana':'りようする', 'meaning':'lợi dụng', 'hannom':''},
{'kanji' :'不便な', 'hiragana':'ふべんな', 'meaning':'BẤT Lợi', 'hannom':''},
{'kanji' :'不足する', 'hiragana':'ふそくする', 'meaning':'Bất Túc - thiếu thốn', 'hannom':''},
{'kanji' :'不運な', 'hiragana':'ふうんな', 'meaning':'Bất Vận - k may', 'hannom':''},
{'kanji' :'不親切な', 'hiragana':'ふしんせつな', 'meaning':'Bất Thân Thiết', 'hannom':''},
{'kanji' :'若い', 'hiragana':'わかい', 'meaning':'NHƯỢC - nhỏ', 'hannom':''},
{'kanji' :'若者', 'hiragana':'わかもの', 'meaning':'Nhược Giả - người trẻ', 'hannom':''},
{'kanji' :'若さ', 'hiragana':'わかさ', 'meaning':'trẻ tuổi', 'hannom':''},
{'kanji' :'早い', 'hiragana':'はやい', 'meaning':'TẢO - sớm', 'hannom':''},
{'kanji' :'早朝', 'hiragana':'そうちょう', 'meaning':'Tảo Triều - sáng sớm', 'hannom':''},
{'kanji' :'早く', 'hiragana':'はやく', 'meaning':'sự sớm (Adv)', 'hannom':''},
{'kanji' :'忙しい', 'hiragana':'いそがしい', 'meaning':'MANG - bận rộn', 'hannom':''},
{'kanji' :'多忙な', 'hiragana':'たぼうな', 'meaning':'Đa Mang - rất bận', 'hannom':''},


];