var kanji1314 = [
	{'kanji' :'近所', 'hiragana':'きんじょ', 'meaning':'hàng xóm', 'hannom':''},
{'kanji' :'遠足', 'hiragana':'えんそく', 'meaning':'picnic', 'hannom':''},
{'kanji' :'速い', 'hiragana':'はやい', 'meaning':'TỐC - nhanh', 'hannom':''},
{'kanji' :'速度', 'hiragana':'そくど', 'meaning':'tốc độ', 'hannom':''},
{'kanji' :'速達', 'hiragana':'そくたつ', 'meaning':'chuyển phát nhanh', 'hannom':''},
{'kanji' :'遅い', 'hiragana':'おそい', 'meaning':'TRÌ - chậm', 'hannom':''},
{'kanji' :'遅れる', 'hiragana':'おくれる', 'meaning':'trễ', 'hannom':''},
{'kanji' :'遅刻する', 'hiragana':'ちこくする', 'meaning':'đến trễ', 'hannom':''},
{'kanji' :'道', 'hiragana':'みち', 'meaning':'ĐẠO - con đường', 'hannom':''},
{'kanji' :'水道', 'hiragana':'すいどう', 'meaning':'nước máy', 'hannom':''},
{'kanji' :'歩道', 'hiragana':'ほどう', 'meaning':'vỉa hè', 'hannom':''},
{'kanji' :'車道', 'hiragana':'しゃどう', 'meaning':'lòng đường', 'hannom':''},
{'kanji' :'青信号', 'hiragana':'あおしんごう', 'meaning':'ánh sáng màu xanh lá cây', 'hannom':''},
{'kanji' :'青年', 'hiragana':'せいねん', 'meaning':'thanh niên', 'hannom':''},
{'kanji' :'晴れ', 'hiragana':'はれ', 'meaning':'TÌNH - trời đẹp', 'hannom':''},
{'kanji' :'晴れる', 'hiragana':'はれる', 'meaning':'trời đẹp ', 'hannom':''},
{'kanji' :'晴天', 'hiragana':'せいてん', 'meaning':'thời tiết đẹp', 'hannom':''},
{'kanji' :'静かな', 'hiragana':'しずかな', 'meaning':'TĨNH - yên tĩnh', 'hannom':''},
{'kanji' :'静まる', 'hiragana':'しずまる', 'meaning':'lắng (V)', 'hannom':''},
{'kanji' :'静止する', 'hiragana':'せいしする', 'meaning':'đứng yên ', 'hannom':''},
{'kanji' :'東大寺', 'hiragana':'とうだいじ', 'meaning':'ĐÔNG ĐẠI TỰ', 'hannom':''},
{'kanji' :'持続する', 'hiragana':'じぞくする', 'meaning':'kéo dài/ tiếp tục', 'hannom':''},
{'kanji' :'荷作りする', 'hiragana':'にづくりする', 'meaning':'đóng gói', 'hannom':''},
{'kanji' :'広告', 'hiragana':'こうこく', 'meaning':'quảng cáo', 'hannom':''},
{'kanji' :'速度', 'hiragana':'そくど', 'meaning':'tốc độ', 'hannom':''},
{'kanji' :'疲れる', 'hiragana':'つかれる', 'meaning':'mệt mỏi', 'hannom':''},
{'kanji' :'疲れ', 'hiragana':'つかれ', 'meaning':'sự mệt mỏi', 'hannom':''},
{'kanji' :'痛み止め', 'hiragana':'いたみどめ', 'meaning':'thuốc giảm đau', 'hannom':''},
{'kanji' :'頭痛', 'hiragana':'ずつう', 'meaning':'đau đầu', 'hannom':''},
{'kanji' :'屋上', 'hiragana':'おくじょう', 'meaning':'mái nhà', 'hannom':''},
{'kanji' :'国立大学', 'hiragana':'こくりつだいがく', 'meaning':'ĐH quốc gia', 'hannom':''},
{'kanji' :'回す', 'hiragana':'まわす', 'meaning':'quây', 'hannom':''},
{'kanji' :'回る', 'hiragana':'まわる', 'meaning':'xoay', 'hannom':''},
{'kanji' :'困る', 'hiragana':'こまる', 'meaning':'khó khăn/ lo lắng', 'hannom':''},
{'kanji' :'困難な', 'hiragana':'こんなんな', 'meaning':'khó', 'hannom':''},
{'kanji' :'開く', 'hiragana':'ひらく', 'meaning':'mở lớp học', 'hannom':''},
{'kanji' :'開ける', 'hiragana':'あける', 'meaning':'đóng', 'hannom':''},
{'kanji' :'開会する', 'hiragana':'かいかいする', 'meaning':'khai hội', 'hannom':''},
{'kanji' :'開店する', 'hiragana':'かいてんする', 'meaning':'khai trương', 'hannom':''},
{'kanji' :'閉まる', 'hiragana':'しまる', 'meaning':'đóng cửa', 'hannom':''},
{'kanji' :'閉じる', 'hiragana':'とじる', 'meaning':'kết thúc', 'hannom':''},
{'kanji' :'閉める', 'hiragana':'しめる', 'meaning':'đóng, gài', 'hannom':''},
{'kanji' :'閉会する', 'hiragana':'へいかいする', 'meaning':'bế mạc hội nghị', 'hannom':''},
{'kanji' :'閉店する', 'hiragana':'へいてんする', 'meaning':'đóng cửa hàng', 'hannom':''},

];